---
networks:
  qlever_network:
      name: qlever-network-${QLEVER_NET:-base}
      external: true
  treafik_proxy:
      name: treafik_proxy
      external: true
#export USER_ID=$(id -u)
#export GROUP_ID=$(id -g)
configs:
  qlever-config:
    name: glever-config-${PROJECT:-geocodes_examples}

services:

 qlever.server.project:
    image: docker.io/adfreiburg/qlever:latest
    container_name: qlever.server.${PROJECT:-deepoceans}
    hostname:
    init: true
    user: "1000:1000"  # Will be set via .env file
    working_dir: /data
    ports:
      - "7019:7019"
    environment:
      - PATH="/qlever:/qlever/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - LANG="C.UTF-8"
      - LC_ALL="C.UTF-8"
      - LC_CTYPE="C.UTF-8"
      - DEBIAN_FRONTEND="noninteractive"
      - QLEVER_PROFILE="/etc/profile.d/qlever.sh"
      - QLEVER_ARGCOMPLETE_ENABLED="1"
      - QLEVER_IS_RUNNING_IN_CONTAINER="1"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/fils/scratch/qleverflow/configs/marineregions:/data
    entrypoint: /qlever/docker-entrypoint.sh
    command: >
      -c 'ServerMain -i marineregions -j 8 -p 7019 -m 25G -c 20G -e 1G -k 200 -s 240s'
    restart: unless-stopped
    networks: &network
      - qlever_network
      - treafik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qlever-project-${PROJECT:-geocodesexamples}.entrypoints=http"
      - "traefik.http.routers.qlever-project-${PROJECT:-geocodesexamples}.rule=Host(`qlever-${PROJECT:-geocodesexamples}.${HOST}`)"
      - "traefik.http.middlewares.qlever-project-${PROJECT:-geocodesexamples}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.qlever-project-${PROJECT:-geocodesexamples}.middlewares=qlever-project-${PROJECT:-geocodesexamples}-https-redirect"
      - "traefik.http.routers.qlever-project-${PROJECT:-geocodesexamples}-secure.entrypoints=https"
      - "traefik.http.routers.qlever-project-${PROJECT:-geocodesexamples}-secure.rule=Host(`qlever-${PROJECT:-geocodesexamples}.${HOST}`)"
      - "traefik.http.routers.qlever-project-${PROJECT:-geocodesexamples}-secure.tls=true"
      - "traefik.http.routers.qlever-project-${PROJECT:-geocodesexamples}-secure.tls.certresolver=httpresolver"
      - "traefik.http.routers.qlever-project-${PROJECT:-geocodesexamples}-secure.service=qlever-project-${PROJECT:-geocodesexamples}"
      - "traefik.http.services.qlever-project-${PROJECT:-geocodesexamples}.loadbalancer.server.port=7019"
      - "traefik.docker.network=traefik_proxy"





