### basic services and a single container for qlver
# PROJECT MUST BE A DNS COMPLAINT NAME. NO UNDER_SCORES
# Environment variables need to be set in a .env file:
version: '3.9'
networks:
  qlever_network:
      name: qlever_network_${QLEVER_NET:-base}
      external: true
  traefik_proxy:
      name: traefik_proxy
      external: true
#export USER_ID=$(id -u)
#export GROUP_ID=$(id -g)
volumes:
  qleverflow_data:
    name: qleverflow_data_${PROJECT:-services}
    #name: qlever
  release_data:
    name: release_data
    external: true
configs:
  qlever_ui_config:
    name: qlever-ui-config-${QLEVER_UI_CONFIG:-services}
    #file: /Users/valentin/development/dev_earthcube/qleverflow/catalogues/data-geocodesexamples/Qleverfile.geocodesexamples
    external: true
services:


 qlever-ui-new-base:
    image: ghcr.io/qlever-dev/qlever-ui-new:edge
    hostname: qlever-ui-new-${PROJECT:-services}
    #init: true
    volumes:
      - type: volume
        source: qleverflow_data
        target: /app/db/
    #   - qleverflow_data:/app/db
    # ports:
    #   - "8176:7000"
    environment:
      # this will hopefully be a hostname from the above service
      QLEVER_HOST: "http://qlever-server-${PROJECT:-geocodesexamples}:7007"
      QLEVERUI_ALLOWED_HOSTS: "*"
      QLEVERUI_CSRF_TRUSTED_ORIGINS: ${QLEVERUI_CSRF_TRUSTED_ORIGINS:-https://*.geocodes-aws-dev.earthcube.org}
      QLEVERUI_SECRET_KEY: ${QLEVERUI_SECRET_KEY:-!!super_secret!!}
      QLEVERUI_DATABASE_URL: "sqlite:////app/db/qleverui.sqlite3"
#      QLEVER_HOST: "http://0.0.0.0:7007"
   #    entrypoint: bash
    command:
      - gunicorn
      - "--bind"
      - ":7000"
      - "--workers"
      - "3"
      - "--limit-request-line"
      - "10000"
      - "qlever.wsgi:application"
    #restart: unless-stopped
    configs:
         - source: qlever_ui_config
           target: /app/data/config.yaml
    networks: &network
      - qlever_network
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qlever-uinew--${PROJECT:-services}.entrypoints=http"
      - "traefik.http.routers.qlever-uinew-${PROJECT:-services}.rule=Host(`qlever-uinew.${HOST}`)"
      - "traefik.http.middlewares.qlever-uinew-${PROJECT:-services}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.qlever-uinew-${PROJECT:-services}.middlewares=qlever-uinew-${PROJECT:-services}-https-redirect"
      - "traefik.http.routers.qlever-uinew-${PROJECT:-services}-secure.entrypoints=https"
      - "traefik.http.routers.qlever-uinew-${PROJECT:-services}-secure.rule=Host(`qlever-uinew.${HOST}`)"
      - "traefik.http.routers.qlever-uinew-${PROJECT:-services}-secure.tls=true"
      - "traefik.http.routers.qlever-uinew-${PROJECT:-services}-secure.tls.certresolver=httpresolver"
      - "traefik.http.routers.qlever-uinew-${PROJECT:-services}-secure.service=qlever-uinew-${PROJECT:-services}"
      - "traefik.http.services.qlever-uinew-${PROJECT:-services}.loadbalancer.server.port=7000"
      - "traefik.docker.network=traefik_proxy"


