networks:
  qlever_network:
    name: qlever_net
#      external: true

#export USER_ID=$(id -u)
#export GROUP_ID=$(id -g)

volumes:
  ql_dvol:

services:
  qlever.server:
    image: docker.io/adfreiburg/qlever:latest
    container_name: qlever.server
    init: true
    user: "1000:1000" # Will be set via .env file
    working_dir: /data
    ports:
      - "7007:7007"
    environment:
      - PATH="/qlever:/qlever/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - LANG="C.UTF-8"
      - LC_ALL="C.UTF-8"
      - LC_CTYPE="C.UTF-8"
      - DEBIAN_FRONTEND="noninteractive"
      - QLEVER_PROFILE="/etc/profile.d/qlever.sh"
      - QLEVER_ARGCOMPLETE_ENABLED="1"
      - QLEVER_IS_RUNNING_IN_CONTAINER="1"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ql_dvol:/data
    entrypoint: /qlever/docker-entrypoint.sh
    command: >
      -c 'ServerMain -i odis -j 8 -p 7007 -m 25G -c 20G -e 1G -k 200 -s 240s -t'
    restart: unless-stopped
  #    networks:
  #      - qlever_network

  # need to add in docker exec -i qlever.ui.odis bash -c "python manage.py config default /app/db/Qleverfile-ui.yml --hide-all-other-backends"
  qlever.ui:
    image: docker.io/adfreiburg/qlever-ui:latest
    container_name: qlever.ui
    init: true
    user: "1000:1000" # Will be set via .env file
    volumes:
      - ql_dvol:/app/db
    ports:
      - "8176:7000"
    environment:
      # this will hopefully be a hostname from the above service
      #      QLEVER_HOST: "http://qlever-server-${PROJECT:-geocodesexamples}:7007"
      #      QLEVERUI_ALLOWED_HOSTS: "*"
      #      QLEVERUI_CSRF_TRUSTED_ORIGINS: "https://*.geocodes-aws-dev.earthcube.org"
      #      QLEVERUI_SECRET_KEY: ${QLEVERUI_SECRET_KEY:-!!super_secret!!}
      QLEVER_HOST: "http://oih.ioc-africa.org:7007" # Updated to use service name
      QLEVERUI_DATABASE_URL: "sqlite:////app/db/odis.ui-db.sqlite3"
#      QLEVER_HOST: "http://192.168.202.191:7007" # Updated to use service name
    #    entrypoint: bash
    command:
      - gunicorn
      - "--bind"
      - ":7000"
      - "--workers"
      - "3"
      - "--limit-request-line"
      - "10000"
      - "qlever.wsgi:application"
    restart: unless-stopped
  #    networks:
  #      - qlever_network

  qlever.petrimaps:
    image: docker.io/adfreiburg/qlever-petrimaps:latest
    container_name: qlever.ui.petrimaps
    hostname: qlever-petrimaps
    ports:
      - "9090:9090"
#    networks:
#      - qlever_network
